/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package restaurante_grupo41.Vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restaurante_grupo41.Datos.MeseroData;
import restaurante_grupo41.Entidades.Mesero;

public class VistaMesero extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMesero
     */
    public VistaMesero(Mesero mesero) {
        initComponents();
       
        cargarTexto (mesero);
        if(mesero.isAdministrador()){
        cargarTabla ();
        cargarDatos();
       
         
        }
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbAgregar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtIdMesero = new javax.swing.JTextField();
        jBAsignarAdministrador = new javax.swing.JButton();
        jBEliminarAdministrador = new javax.swing.JButton();
        jLAdministrador = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTPass = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(246, 245, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbAgregar.setBackground(new java.awt.Color(236, 178, 46));
        jbAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbAgregar.setText("Agregar");
        jbAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbModificar.setBackground(new java.awt.Color(236, 178, 46));
        jbModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbModificar.setText("Modificar");
        jbModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setBackground(new java.awt.Color(236, 178, 46));
        jbEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbBuscar.setBackground(new java.awt.Color(236, 178, 46));
        jbBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbVolver.setBackground(new java.awt.Color(236, 178, 46));
        jbVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbVolver.setText("Volver");
        jbVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("ID");

        jtIdMesero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtIdMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdMeseroActionPerformed(evt);
            }
        });

        jBAsignarAdministrador.setBackground(new java.awt.Color(236, 178, 46));
        jBAsignarAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBAsignarAdministrador.setText("Asignar");
        jBAsignarAdministrador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAsignarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsignarAdministradorActionPerformed(evt);
            }
        });

        jBEliminarAdministrador.setBackground(new java.awt.Color(236, 178, 46));
        jBEliminarAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBEliminarAdministrador.setText("Remover");
        jBEliminarAdministrador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBEliminarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarAdministradorActionPerformed(evt);
            }
        });

        jLAdministrador.setBackground(new java.awt.Color(236, 178, 46));
        jLAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAdministrador.setText("ADMINISTRADOR");
        jLAdministrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLAdministrador.setOpaque(true);

        jTNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Nombre");

        jLabel4.setText("Usuario");

        jTUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Contraseña");

        jTPass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addComponent(jbAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBEliminarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBAsignarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtIdMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTPass, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(282, 282, 282))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))))
            .addComponent(jLAdministrador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtIdMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jLabel3)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificar)
                    .addComponent(jLabel4)
                    .addComponent(jTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEliminar)
                    .addComponent(jLabel5)
                    .addComponent(jTPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jbVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBAsignarAdministrador)
                        .addGap(37, 37, 37)
                        .addComponent(jBEliminarAdministrador)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAsignarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsignarAdministradorActionPerformed
      MeseroData medat=new MeseroData();
       int filas = jTable1.getSelectedRow();
          if (filas != -1){
         int id=(int) modelo.getValueAt(filas,3);
        
         Mesero mesero= medat.buscarMeseroPorId(id);
         medat.agregarAdministrador(mesero);
          }
    }//GEN-LAST:event_jBAsignarAdministradorActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        
       
        MeseroData medat= new MeseroData ();
         String nombre=jTNombre.getText().trim();
         String usuario= jTUsuario.getText().trim();
         String pass= jTPass.getText().trim();
         
         Mesero mesero= new Mesero (nombre, usuario, pass);
         medat.agregarMesero(mesero);
         cargarDatos();
         jTable1.repaint();
         
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jBEliminarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarAdministradorActionPerformed
     MeseroData medat=new MeseroData();
       int filas = jTable1.getSelectedRow();
          if (filas != -1){
         int id=(int) modelo.getValueAt(filas,3);
        
         Mesero mesero= medat.buscarMeseroPorId(id);
         medat.eliminarAdministrador(mesero);
          }
          cargarDatos ();
           jTable1.repaint();
    }//GEN-LAST:event_jBEliminarAdministradorActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
MeseroData medat = new MeseroData();

    String nombre = jTNombre.getText().trim();
    String usuario = jTUsuario.getText().trim();
    String pass = jTPass.getText().trim();
    String idText = jtIdMesero.getText().trim();

    // Validar que el id sea un número entero
    try {
        int id = Integer.parseInt(idText);
        
        // Validar que el nombre no contenga números
        if (!nombre.matches(".*\\d+.*")) {
            Mesero mesero = new Mesero(nombre, usuario, pass, id);
            medat.modificarMesero(mesero);
        } else {
            JOptionPane.showMessageDialog(null, "El nombre no debe contener números.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El id debe ser un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    cargarDatos();
    jTable1.repaint();
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
       
        try{
         MeseroData medat= new MeseroData ();
        String nombre=jTNombre.getText().trim();
        String usuario= jTUsuario.getText().trim();
        String pass= jTPass.getText().trim();
        int id= Integer.parseInt(jtIdMesero.getText().trim());
       
        Mesero mesero= new Mesero (nombre,usuario, pass, id);
        
        medat.eliminarMesero(id);
         } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El id debe ser  un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        cargarDatos();
        jTable1.repaint();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        dispose ();
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
      
        try {

            int id = Integer.parseInt(jtIdMesero.getText().trim());
            MeseroData mesdata = new MeseroData();
            Mesero mesero = mesdata.buscarMeseroPorId(id);
            if (mesero != null) {
                jTNombre.setText(mesero.getNombre());
                jTUsuario.setText(mesero.getUsuario());
                jTPass.setText(mesero.getPass());
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El id debe ser  un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         
         
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtIdMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdMeseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdMeseroActionPerformed

    
    public void cargarTexto (Mesero m){
       
        Integer id= m.getIdMesero();
        jtIdMesero.setText(id.toString());
        jTNombre.setText(m.getNombre());
        jTUsuario.setText(m.getUsuario());
        jTPass.setText("");
        
        
        if (m.isAdministrador()){
          jbBuscar.setVisible(true);
          jbAgregar.setVisible(true);
          jbEliminar.setVisible(true);
        jBAsignarAdministrador.setVisible(true);
        jBEliminarAdministrador.setVisible(true);
        jTable1.setVisible(true);
        cargarDatos();
        
        }else{
         jbBuscar.setVisible(false);
          jbAgregar.setVisible(false);
          jbEliminar.setVisible(false);
        jBAsignarAdministrador.setVisible(false);
        jBEliminarAdministrador.setVisible(false);
        jTable1.setVisible(false);   
         jLAdministrador.setVisible(false);
        jtIdMesero.setEditable(false);
        }
        
    }
    private DefaultTableModel modelo = new DefaultTableModel();

    public void cargarTabla (){
        modelo.addColumn ("Nombre");
        modelo.addColumn ("Usuario");
        modelo.addColumn ("Contraseña");
        modelo.addColumn ("Id");
        modelo.addColumn("Administrador");
        jTable1.setModel(modelo);
    }
    
    public void cargarDatos (){
        
    jTable1.getModel();
        modelo.setRowCount(0);
       jTable1.repaint();
      
       MeseroData md = new MeseroData();
        ArrayList<Mesero> meseros = md.ListaMesero();
       
        
        for (Mesero mesero: meseros) {
           
            modelo.addRow(new Object[]{ mesero.getNombre(),mesero.getUsuario(),mesero.getPass(),mesero.getIdMesero(), mesero.isAdministrador() });
        }

    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAsignarAdministrador;
    private javax.swing.JButton jBEliminarAdministrador;
    private javax.swing.JLabel jLAdministrador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTPass;
    private javax.swing.JTextField jTUsuario;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbVolver;
    private javax.swing.JTextField jtIdMesero;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
