
package restaurante_grupo41.Vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restaurante_grupo41.Datos.MesaData;
import restaurante_grupo41.Datos.PedidoData;
import restaurante_grupo41.Entidades.Mesa;
import restaurante_grupo41.Entidades.Pedido;


public class VistaMesa extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMesa
     */
    public VistaMesa() {
        initComponents();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpVistaMesa = new javax.swing.JPanel();
        jbAgregar = new javax.swing.JButton();
        jBmLibres = new javax.swing.JButton();
        jbOcupada = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbAtendida = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaMesas = new javax.swing.JTable();
        jbVolver = new javax.swing.JButton();
        jlMesas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTfcap = new javax.swing.JTextField();
        jBAsignar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setPreferredSize(new java.awt.Dimension(730, 620));

        jpVistaMesa.setPreferredSize(new java.awt.Dimension(734, 624));

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jBmLibres.setText("Libres");
        jBmLibres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmLibresActionPerformed(evt);
            }
        });

        jbOcupada.setText("Ocupadas");
        jbOcupada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOcupadaActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbAtendida.setText("Atendida");
        jbAtendida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtendidaActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jtListaMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero", "Capacidad", "Atendida", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaMesas);

        jbVolver.setText("Volver");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        jlMesas.setText("Mesas");

        jLabel1.setText("capacidad");

        jTfcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfcapActionPerformed(evt);
            }
        });

        jBAsignar.setText("Asignar");
        jBAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpVistaMesaLayout = new javax.swing.GroupLayout(jpVistaMesa);
        jpVistaMesa.setLayout(jpVistaMesaLayout);
        jpVistaMesaLayout.setHorizontalGroup(
            jpVistaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVistaMesaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpVistaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jBmLibres, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbOcupada, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(jbAtendida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(jpVistaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(jpVistaMesaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59)
                        .addComponent(jTfcap, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpVistaMesaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );
        jpVistaMesaLayout.setVerticalGroup(
            jpVistaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVistaMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpVistaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpVistaMesaLayout.createSequentialGroup()
                        .addGroup(jpVistaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpVistaMesaLayout.createSequentialGroup()
                                .addComponent(jlMesas)
                                .addGap(68, 68, 68)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                            .addGroup(jpVistaMesaLayout.createSequentialGroup()
                                .addComponent(jBmLibres)
                                .addGap(18, 18, 18)
                                .addComponent(jbOcupada)
                                .addGap(18, 18, 18)
                                .addComponent(jbAtendida)
                                .addGap(18, 18, 18)
                                .addComponent(jbLimpiar)
                                .addGap(26, 26, 26)
                                .addComponent(jbEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(jBAsignar)
                                .addGap(18, 18, 18)
                                .addComponent(jbVolver)
                                .addGap(59, 59, 59)))
                        .addComponent(jbAgregar))
                    .addGroup(jpVistaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTfcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpVistaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpVistaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsignarActionPerformed
        MesaData md = new MesaData();
        int filas = jtListaMesas.getSelectedRow();
        if (filas != -1){
            int nro=(int) modelo.getValueAt(filas,0);
            md.ocuparMesa(nro);
        }
        cargarDatos();
        jtListaMesas.repaint();
    }//GEN-LAST:event_jBAsignarActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        MesaData md = new MesaData();
        int filas = jtListaMesas.getSelectedRow();
        if (filas != -1){
            int nro=(int) modelo.getValueAt(filas,0);
            md.limpiarMesa(nro);
        }
        cargarDatos();
        jtListaMesas.repaint();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbAtendidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtendidaActionPerformed
        MesaData md = new MesaData();
        int filas = jtListaMesas.getSelectedRow();
        if (filas != -1){
            int nro=(int) modelo.getValueAt(filas,0);
            md.mesaAtendida(nro);
        }
        cargarDatos();
        jtListaMesas.repaint();
    }//GEN-LAST:event_jbAtendidaActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        MesaData md = new MesaData();
        int filas = jtListaMesas.getSelectedRow();
        if (filas != -1){
            int nro=(int) modelo.getValueAt(filas,0);
            md.eliminarMesa(nro);
        }
        cargarDatos();
        jtListaMesas.repaint();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbOcupadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOcupadaActionPerformed
        jtListaMesas.getModel();
        modelo.setRowCount(0);
        jtListaMesas.repaint();
        MesaData md = new MesaData();
        PedidoData pd = new PedidoData();
        double total;
        ArrayList<Mesa> mesas = md.listaMesasOcupadas();
        for (Mesa ms : mesas) {
            Pedido pedido = pd.buscarPedidoMesa(ms.getNumero());
            if (pedido == null) {
                total = 0;
            } else {
                total = pedido.getTotal();
            }

            modelo.addRow(new Object[]{ms.getNumero(), ms.getCapacidad(), ms.isAtendida(), total});
        }
    }//GEN-LAST:event_jbOcupadaActionPerformed

    private void jBmLibresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmLibresActionPerformed
        jtListaMesas.getModel();
        modelo.setRowCount(0);
        jtListaMesas.repaint();
        MesaData md = new MesaData();
        PedidoData pd = new PedidoData();
        ArrayList<Mesa> mesas = md.listaMesasLibres();
        double total;
        for (Mesa ms : mesas) {
            Pedido pedido = pd.buscarPedidoMesa(ms.getNumero());
            if (pedido == null) {
                total = 0;
            } else {
                total = pedido.getTotal();
            }

            modelo.addRow(new Object[]{ms.getNumero(), ms.getCapacidad(), ms.isAtendida(), total});
        }
    }//GEN-LAST:event_jBmLibresActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed

         try {
        
        int cap = Integer.parseInt(jTfcap.getText().trim());
        if(cap>9||cap<0){
               JOptionPane.showMessageDialog(null, "La Capacidad maxima es de 8 personas.", "Error", JOptionPane.ERROR_MESSAGE);

        }else{
         MesaData md=new MesaData();
        Mesa mesa = new Mesa(cap);
        md.agregarMesas(mesa);
        cargarDatos();
        jtListaMesas.repaint();
        }
       
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "La Capacidad deber ser  un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }
        
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jTfcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfcapActionPerformed
       
        

// TODO add your handling code here:
    }//GEN-LAST:event_jTfcapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMesa().setVisible(true);
            }
        });
    }

    private DefaultTableModel modelo = new DefaultTableModel();

    public void CargarTabla() {
        modelo.addColumn("numero");
        modelo.addColumn("capacidad");
        modelo.addColumn("atendida");
        modelo.addColumn("total");
        jtListaMesas.setModel(modelo);
    }

    public void cargarDatos() {
        jtListaMesas.getModel();
        modelo.setRowCount(0);
        jtListaMesas.repaint();
        MesaData md = new MesaData();

        ArrayList<Mesa> mesas = md.listaMesas();
        PedidoData pd = new PedidoData();
        for (Mesa ms : mesas) {
            Pedido pedido = pd.buscarPedidoMesa(ms.getNumero());
            double total;

            if (pedido == null) {
                total = 0;
            } else {
                total = pedido.getTotal();
            }

            modelo.addRow(new Object[]{ms.getNumero(), ms.getCapacidad(), ms.isAtendida(), total});
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAsignar;
    private javax.swing.JButton jBmLibres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTfcap;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbAtendida;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbOcupada;
    private javax.swing.JButton jbVolver;
    private javax.swing.JLabel jlMesas;
    private javax.swing.JPanel jpVistaMesa;
    private javax.swing.JTable jtListaMesas;
    // End of variables declaration//GEN-END:variables
}
